eureka:
    client:
        service-url:
            defaultZone: http://netflix:eureka@localhost:8761/eureka
logging:
    level:
        root: info
server:
    port: 8081
spring:
    application:
        name: product-service
    artemis:
        password: simetraehcapa
        user: artemis
    cloud:
        config:
            discovery:
                enabled: true
                service-id: product-service
        discovery:
            enabled: true
    data:
        mongodb:
            database: store-product
            port: 27017
    profiles:
        active: discovery
store:
    rest:
        inventory-base-url: http://localhost:8083
        product-QOH-url-by-id: api/v1/inventory/{productId}/id
        product-QOH-url-by-upc: api/v1/inventory/{upc}/upc
